server:
  port: 8701
  servlet:
    # 配置项目名称（默认为 /），如果配置了项目名称，那么在访问路径中要加上配置的路径
    context-path: /
    session:
      # 服务器session最大超时时间(分钟)
      timeout: 30m
  # tomcat配置
  tomcat:
    # tomcat根目录
    # basedir: D:/
    # tomcat字符集
    uri-encoding: UTF-8
    # tomcat最大连接数
    max-connections: 2000
    accept-count: 5000
    # tomcat最大线程数
    max-threads: 1000
    # 最大连接超时时间
    connection-timeout: 100
    accesslog:
      # 启用访问日志
      enabled: true
      # 访问日志的格式模式
      pattern: common
      # 是否缓冲输出，使其仅定期刷新
      buffered: true
      # 创建日志文件的目录。可以绝对或相对于Tomcat基础目录（整体一定是绝对路径，windows要加盘符）
      directory: D:/Users/allen/Develop/logs/${spring.application.name}
      # directory: /Users/allen/Develop/logs/${spring.application.name}
      # 日志文件名前缀
      prefix: ${spring.application.name}-access-
      # 要放在日志文件名中的日期格式
      file-date-format: yyyy-MM-dd
       # 日志文件名后缀
      suffix: .log
      # 是否延迟在文件名中包含日期戳，直到旋转时间
      rename-on-rotate: false
      # 设置请求的IP地址，主机名，协议和端口的请求属性
      request-attributes-enabled: false
      # 是否启用访问日志轮换
      rotate: true
      
spring:  application:    name: allen-eureka-server
  security:    user:      name: allen
      password: allen1234
    
eureka:
  instance:    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    # true：实例以 IP 的形式注册；false：实例以机器 HOSTNAME 形式注册
    prefer-ip-address: true
    # 表示 Eureka Server 在接收到上一个心跳之后等待下一个心跳的秒数（默认 90 秒），
    # 若不能在指定时间内收到心跳，则移除此实例，并禁止此实例的流量。
    # 需要设置为至少高于 lease-renewal-interval-in-seconds 的值，不然会被误移除了。
    lease-expiration-duration-in-seconds: 30
    # 表示 Eureka Client 向 Eureka Server 发送心跳的频率（默认 30 秒），
    # 如果在 lease-expiration-duration-in-seconds 指定的时间内未收到心跳，则移除该实例。
    lease-renewal-interval-in-seconds: 10  client:
    # Eureka Client 刷新本地缓存时间，默认30秒
    registry-fetch-interval-seconds: 5
    # 表示是否将自己注册到Eureka Server，默认为true。单机模式下设置为false，仅作为服务中心，不作为服务客户端    register-with-eureka: false 
    # 表示是否从Eureka Server获取注册信息，默认为true。单机模式下设置为false， 不从服务中心检索注册的服务
    fetch-registry: false
    # 表示客户端需要注册的 Eureka Server 的地址。
    service-url:
      defaultZone: http://allen:allen1234@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 是否开启readOnlyCacheMap(ConcurrentHashMap)
    use-read-only-response-cache: true
    # 调整readWriteCacheMap(Guava Cache)的过期时间，默认180秒
    response-cache-auto-expiration-in-seconds: 60
    # 清理无效节点的频率（单位毫秒， 默认是60*1000）
    eviction-interval-timer-in-ms: 5000
    # 默认为true，设置为false，关闭自我保护，开发环境设置为false
    enable-self-preservation: false
    # Eureka Server 在运行期间会去统计心跳失败比例在15分钟之内是否低于85%，#默认0.85
    renewal-percent-threshold: 0.49
    
logging:
  level:
    org:
      apache:
        catalina: DEBUG
        tomcat: DEBUG